ARDUINO_DIR = F:\Dropbox\bin\arduino-1.0
PARSE_BOARD = ard-parse-boards

BOARD_TAG    = atmega328
MCU          = atmega328p
F_CPU        = 16000000L
ARDUINO_PORT = COM7
ARD_PORT     = COM7
AVRDUDE_ARD_PROGRAMMER = arduino
AVRDUDE_ARD_BAUDRATE = 57600

ARDUINO_LIBS = Firmata Servo Wire

include Arduino.mk