Govorilka_cp.exe -E "Adult Male #1, American English (TruVoice)" "Hello! I am your computer!"
Govorilka_cp.exe -E "Adult Female #1, American English (TruVoice)" "Hello! I am your sound card!"
Govorilka_cp.exe -P0 -E "Adult Female #1, American English (TruVoice)" "1"
Govorilka_cp.exe -P10 -E "Adult Female #1, American English (TruVoice)" "2"
Govorilka_cp.exe -P20 -E "Adult Female #1, American English (TruVoice)" "3"
Govorilka_cp.exe -P30 -E "Adult Female #1, American English (TruVoice)" "4"
Govorilka_cp.exe -P40 -E "Adult Female #1, American English (TruVoice)" "5"
Govorilka_cp.exe -P50 -E "Adult Female #1, American English (TruVoice)" "6"
Govorilka_cp.exe -P60 -E "Adult Female #1, American English (TruVoice)" "7"
Govorilka_cp.exe -P70 -E "Adult Female #1, American English (TruVoice)" "8"
Govorilka_cp.exe -P80 -E "Adult Female #1, American English (TruVoice)" "9"
Govorilka_cp.exe -P90 -E "Adult Female #1, American English (TruVoice)" "10"
Govorilka_cp.exe -P100 -E "Adult Female #1, American English (TruVoice)" "Oh my voice!"
